

name_tool       =  "IRC"
type_tool       =  "Multi-Tools"
version_tool    =  "1.0"
coding_tool     =  "Python 3"
language_tool   =  "EN"
creator         =  "vaslekarr"
platform        =  "Windows 10/11 & Linux"
website         =  "None"
github_tool     =  "https://github.com/amirrepl/amirpishiweb"
telegram        =  "Soon"
gunslol         =  "Soon"
url_config      =  "https://raw.githubusercontent.com/loxy0dev/RedTiger-Tools/main/Program/Config/Config.py"
url_downloads   =  "https://github.com/amirrepl/checkver/releases/download/IRC/Loader.exe"
license         =  "Soon"
copyright       =  "IRC Tool"
